spring:
  application:
    name: email-service

  mail:
    host: ${SPRING_MAIL_HOST:smtp.zoho.in}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_MAIL_STARTTLS_ENABLE:true}
            required: ${SPRING_MAIL_STARTTLS_REQUIRED:true}
        ssl:
          trust: ${SPRING_MAIL_SSL_TRUST:smtp.zoho.in}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL:true}

server:
  port: ${SERVER_PORT:8089}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:https://eureka-server-sk4j.onrender.com/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.value}
    metadata-map:
      management.port: ${server.port}
